[package]
name = "rust_examples"
version = "0.1.0"
authors = ["Hemal Harindaka <hathulathmudali@gmail.com>"]

[dependencies]
rand = "0.3.14"
serde = "1.0.17"
serde_derive = "1.0.17"
serde_json = "1.0.5"